direction: down

svc_0: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **booking**
    - `POST /api/v1/booking/hasAuthority(`
  |
}

svc_1: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **buildingblocks**
  |
}

svc_2: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **flight**
    - `DELETE /api/v1/flight/{id}`
    - `GET /api/v1/flight/get-available-seats/{flightId}`
    - `GET /api/v1/flight/hasAuthority(`
    - `GET /api/v1/flight/{id}`
    - `POST /api/v1/flight/aircraft/hasAuthority(`
    - `POST /api/v1/flight/airport/hasAuthority(`
    - `POST /api/v1/flight/hasAuthority(`
    - `POST /api/v1/flight/reserve-seat/hasAuthority(`
    - `POST /api/v1/flight/seat/hasAuthority(`
    - `PUT /api/v1/flight/{id}`
  |
}

svc_3: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **passenger**
    - `GET /api/v1/passenger/{id}`
    - `POST /api/v1/passenger/hasAuthority(`
  |
}
