direction: down

svc_0: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **hello-kafka-api**
  |
}

svc_1: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **hello-kafka-streams**
  |
}
