direction: down

svc_0: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **application**
    - `GET /api/Retrieve Processes`
    - `GET /api/Retrieve Results`
    - `GET /api/files/{fileId}`
    - `GET /api/generation-results/{id}`
    - `GET /api/processes/{processId}`
    - `POST /api/action/generate`
    - `POST /api/files/upload`
  |
}

svc_1: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **rest-contracts**
  |
}

svc_1 -> svc_0: "POST /api/files/upload" {
}
