direction: down

svc_0: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **microservice-invoicing**
    - `ANY /`
    - `GET /actuator/**`
    - `GET /{id}`
  |
}

svc_1: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **microservice-order**
    - `DELETE /order/{id}`
    - `GET /actuator/**`
    - `GET /api/order`
    - `GET /order`
    - `GET /order/{id}`
    - `GET /swagger-ui.html`
    - `PATCH /order/{id}`
    - `POST /api/order`
    - `POST /order`
    - `PUT /order/{id}`
  |
}

topic_0: {
  label: "order"
  shape: rectangle
  style.fill: "#ffe6cc"
  style.stroke: "#d79b00"
}

svc_1 -> topic_0: "order" {
  style.stroke-dash: 3
}

topic_0 -> svc_0: "order" {
  style.stroke-dash: 3
}
