direction: down

svc_0: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **spring-petclinic-api-gateway**
    - `GET /api/gateway/owners/{ownerId}`
    - `POST /fallback`
  |
}

svc_1: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **spring-petclinic-customers-service**
    - `GET /owners`
    - `GET /owners/*/pets/{petId}`
    - `GET /owners/{ownerId}`
    - `GET /petTypes`
    - `POST /owners`
    - `POST /owners/{ownerId}/pets`
    - `PUT /owners/*/pets/{petId}`
    - `PUT /owners/{ownerId}`
  |
}

svc_2: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **spring-petclinic-genai-service**
    - `POST /chatclient`
  |
}

svc_3: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **spring-petclinic-vets-service**
    - `GET /vets/vets`
  |
}

svc_4: {
  shape: rectangle
  style.fill: "#dae8fc"
  style.stroke: "#6c8ebf"
  label: |md
    **spring-petclinic-visits-service**
    - `GET /owners/*/pets/{petId}/visits`
    - `GET /pets/visits`
    - `POST /owners/*/pets/{petId}/visits`
  |
}

svc_0 -> svc_1: "GET /owners/{ownerId}" {
}

svc_0 -> svc_4: "GET /owners/{ownerId}" {
}

svc_0 -> svc_4: "GET /pets/visits" {
}

svc_2 -> svc_1: "GET /owners" {
}

svc_2 -> svc_4: "GET /owners" {
}

svc_2 -> svc_1: "POST /owners/" {
}

svc_2 -> svc_4: "POST /owners/" {
}

svc_2 -> svc_1: "POST /owners" {
}

svc_2 -> svc_4: "POST /owners" {
}

svc_2 -> svc_3: "GET /vets" {
}
